'use strict';

/**
 * setupConstants.js
 * Constantes partagées du setup wizard.
 * Importé par setupFlow, setupSteps, setupGamesDetect, setupRender, etc.
 */

const TOTAL_STEPS = 9;

const CUSTOM_IDS = Object.freeze({
  start: 'setup:start',
  createRolesAuto: 'setup:grade:create-auto',
  createRolesAll: 'setup:grade:create-all',
  transferExistingRoles: 'setup:grade:transfer-existing',
  recreateRoles: 'setup:grade:recreate',
  renameGradePrefix: 'setup:grade:rename',
  renameGradeModal: 'setup:grade:rename:modal',
  selectOwnerMember: 'setup:grade:owner-member',
  selectRolePrefix: 'setup:grade:role',
  previousGrade: 'setup:grade:prev',
  nextGrade: 'setup:grade:next',
  back: 'setup:step:back',
  toggleSuggestions: 'setup:modules:suggestions:toggle',
  toggleServerList: 'setup:modules:server-list:toggle',
  toggleStatusBot: 'setup:modules:status-bot:toggle',
  toggleAfk: 'setup:modules:afk:toggle',
  toggleGameUpdates: 'setup:modules:game-updates:toggle',
  toggleGuides: 'setup:modules:guides:toggle',
  toggleBioRequired: 'setup:members:bio:toggle',
  toggleSponsorshipRequired: 'setup:members:sponsorship:toggle',
  decreasePromotionDelay: 'setup:members:delay:dec',
  increasePromotionDelay: 'setup:members:delay:inc',
  cyclePromotionReviewerGrade: 'setup:members:reviewer:cycle',
  toggleInviteExpulsion: 'setup:members:invite-expulsion:toggle',
  decreaseInviteExpulsionDays: 'setup:members:invite-expulsion-days:dec',
  increaseInviteExpulsionDays: 'setup:members:invite-expulsion-days:inc',
  editVocalPrefix: 'setup:vocal:prefix:edit',
  editVocalSuffix: 'setup:vocal:suffix:edit',
  toggleVocalSuffix: 'setup:vocal:suffix:toggle',
  decreaseVocalLimit: 'setup:vocal:limit:dec',
  increaseVocalLimit: 'setup:vocal:limit:inc',
  decreaseVocalDelay: 'setup:vocal:delay:dec',
  increaseVocalDelay: 'setup:vocal:delay:inc',
  cycleVocalPrefix: 'setup:vocal:prefix:cycle',
  addGame: 'setup:games:add',
  addGameModal: 'setup:games:add:modal',
  editGamePrefix: 'setup:games:edit',
  editGameModal: 'setup:games:edit:modal',
  deleteGamePrefix: 'setup:games:delete',
  confirmGamePrefix: 'setup:games:confirm',
  toggleGameGallery: 'setup:games:gallery:toggle',
  toggleGameChangelog: 'setup:games:changelog:toggle',
  toggleGameText: 'setup:games:text:toggle',
  toggleGameLayoutMode: 'setup:games:layout:toggle',
  addGameConfirmModal: 'setup:games:add:confirm:modal',
  cycleInviteMode: 'setup:grade:invite:cycle',
  toggleBehaviorScore: 'setup:modules:behavior:toggle',
  decreaseSpamThreshold: 'setup:mod:spam:dec',
  increaseSpamThreshold: 'setup:mod:spam:inc',
  toggleBlacklistWarn: 'setup:mod:blacklist:toggle',
  addBlacklistWord: 'setup:mod:blacklist:add',
  blacklistModal: 'setup:mod:blacklist:modal',
  clearBlacklist: 'setup:mod:blacklist:clear',
  decreaseSlowMode: 'setup:mod:slowmode:dec',
  increaseSlowMode: 'setup:mod:slowmode:inc',
  cycleLogsLevel: 'setup:mod:logs:cycle',
  editWelcomeText: 'setup:members:welcome:edit',
  welcomeModal: 'setup:members:welcome:modal',
  editJoinPresentation: 'setup:members:joinpresentation:edit',
  joinPresentationModal: 'setup:members:joinpresentation:modal',
  channelSelectPrefix: 'setup:channel:select',
  channelSearch: 'setup:channel:search',
  channelSearchModal: 'setup:channel:search:modal',
  channelSearchSelect: 'setup:channel:search:select',
  channelSkip: 'setup:channel:skip',
  next: 'setup:step:next',
  communityCheckContinue: 'setup:community:continue',
  communityCheckRetry: 'setup:community:retry',
  communityCheckHelp: 'setup:community:help',
  gameDetectAdopt: 'setup:gamedetect:adopt',
  gameDetectSkip: 'setup:gamedetect:skip',
  gameLinkNext: 'setup:gamelink:next',
  gameLinkSkip: 'setup:gamelink:skip',
  gameLinkChannelPrefix: 'setup:gamelink:channel',
  gameLinkTypeSelect: 'setup:gamelink:type',
  gamePagePrev: 'setup:games:page:prev',
  gamePageNext: 'setup:games:page:next',
  newOptionsNext: 'setup:newoptions:next',
  newOptionsSkip: 'setup:newoptions:skip',
  finalize: 'setup:finalize',
  confirmOwner: 'setup:grade:owner-confirm',
  securityContinue: 'setup:security:continue',
  securityRoleAction: 'setup:security:role',
  securityDeleteUnused: 'setup:security:unused:delete',
  securityKeepUnused: 'setup:security:unused:keep',
  securityDeleteAllUnused: 'setup:security:unused:delete-all',
  securityKeepAllUnused: 'setup:security:unused:keep-all',
  securityConfirmModal: 'setup:security:confirm-modal',
  clearAllGames: 'setup:games:clear-all',
  channelAutoDetectAccept: 'setup:channel:autodetect:accept',
  channelAutoDetectSkip: 'setup:channel:autodetect:skip',
  notifyMembersYes: 'setup:notify-members:yes',
  notifyMembersNo: 'setup:notify-members:no',
  gameReviewRemovePrefix: 'setup:gamereview:remove:',
  gameReviewAdd: 'setup:gamereview:add',
  gameReviewAddModal: 'setup:gamereview:add:modal',
  gameReviewPrev: 'setup:gamereview:prev',
  gameReviewContinue: 'setup:gamereview:continue',
  prereleaseConfirm: 'setup:prerelease:confirm',
  prereleaseSkip: 'setup:prerelease:skip',
  // @premium-start
  cycleAfkTimeout: 'setup:discord:afk:timeout:cycle',
  cycleSystemChannel: 'setup:discord:syschannel:cycle',
  syncLocale: 'setup:discord:locale:sync',
  applyRulesChannel: 'setup:discord:rules:apply',
  applyPublicUpdates: 'setup:discord:publicupdates:apply',
  editServerDescription: 'setup:discord:description:edit',
  serverDescriptionModal: 'setup:discord:description:modal',
  toggleAutoModRule: 'setup:discord:automod:toggle',
  applyOnboardingChannels: 'setup:discord:onboarding:apply',
  discordSettingsSkip: 'setup:discord:skip',
  // @premium-end
});

module.exports = { CUSTOM_IDS, TOTAL_STEPS };
